// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Constructs a shareable REST-based Bitcoin chain service.
///
/// Pass the returned handle to multiple `SdkBuilder`s via `with_chain_service`
/// to reuse one HTTP client across SDK instances. All SDKs sharing the handle
/// must use the same `network`.
///
/// For one-off, non-shared use, prefer `with_rest_chain_service`.
Future<BitcoinChainServiceHandle> newRestChainService({
  required String url,
  required Network network,
  required ChainApiType apiType,
  Credentials? credentials,
}) => BreezSdkSparkLib.instance.api.crateChainServiceNewRestChainService(
  url: url,
  network: network,
  apiType: apiType,
  credentials: credentials,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<BitcoinChainServiceHandle>>
abstract class BitcoinChainServiceHandle implements RustOpaqueInterface {}
