// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Creates a connection manager.
///
/// `connections_per_operator` controls per-operator connection pooling:
/// `None` keeps a single connection per operator; `Some(n)` opens `n`
/// connections per operator and balances requests across them.
ConnectionManager newConnectionManager({int? connectionsPerOperator}) => BreezSdkSparkLib.instance.api
    .crateConnectionManagerNewConnectionManager(connectionsPerOperator: connectionsPerOperator);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ConnectionManager>>
abstract class ConnectionManager implements RustOpaqueInterface {}
