// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'errors.freezed.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `StorageError`

@freezed
sealed class DepositClaimError with _$DepositClaimError {
  const DepositClaimError._();

  const factory DepositClaimError.maxDepositClaimFeeExceeded({
    required String tx,
    required int vout,
    Fee? maxFee,
    required BigInt requiredFeeSats,
    required BigInt requiredFeeRateSatPerVbyte,
  }) = DepositClaimError_MaxDepositClaimFeeExceeded;
  const factory DepositClaimError.missingUtxo({required String tx, required int vout}) =
      DepositClaimError_MissingUtxo;
  const factory DepositClaimError.generic({required String message}) = DepositClaimError_Generic;
}

@freezed
sealed class PasskeyError with _$PasskeyError implements FrbException {
  const PasskeyError._();

  const factory PasskeyError.prf(PrfProviderError field0) = PasskeyError_Prf;
  const factory PasskeyError.relayConnectionFailed(String field0) = PasskeyError_RelayConnectionFailed;
  const factory PasskeyError.nostrWriteFailed(String field0) = PasskeyError_NostrWriteFailed;
  const factory PasskeyError.nostrReadFailed(String field0) = PasskeyError_NostrReadFailed;
  const factory PasskeyError.keyDerivationError(String field0) = PasskeyError_KeyDerivationError;
  const factory PasskeyError.invalidPrfOutput(String field0) = PasskeyError_InvalidPrfOutput;
  const factory PasskeyError.mnemonicError(String field0) = PasskeyError_MnemonicError;
  const factory PasskeyError.invalidSalt(String field0) = PasskeyError_InvalidSalt;
  const factory PasskeyError.generic(String field0) = PasskeyError_Generic;
}

@freezed
sealed class PrfProviderError with _$PrfProviderError {
  const PrfProviderError._();

  const factory PrfProviderError.prfNotSupported() = PrfProviderError_PrfNotSupported;
  const factory PrfProviderError.userCancelled() = PrfProviderError_UserCancelled;
  const factory PrfProviderError.userTimedOut() = PrfProviderError_UserTimedOut;
  const factory PrfProviderError.credentialNotFound(String field0) = PrfProviderError_CredentialNotFound;
  const factory PrfProviderError.authenticationFailed(String field0) = PrfProviderError_AuthenticationFailed;
  const factory PrfProviderError.prfEvaluationFailed(String field0) = PrfProviderError_PrfEvaluationFailed;
  const factory PrfProviderError.configuration(String field0) = PrfProviderError_Configuration;
  const factory PrfProviderError.credentialAlreadyExists(String field0) =
      PrfProviderError_CredentialAlreadyExists;
  const factory PrfProviderError.generic(String field0) = PrfProviderError_Generic;
}

@freezed
sealed class SdkError with _$SdkError implements FrbException {
  const SdkError._();

  const factory SdkError.sparkError(String field0) = SdkError_SparkError;
  const factory SdkError.insufficientFunds() = SdkError_InsufficientFunds;
  const factory SdkError.invalidUuid(String field0) = SdkError_InvalidUuid;
  const factory SdkError.invalidInput(String field0) = SdkError_InvalidInput;
  const factory SdkError.networkError(String field0) = SdkError_NetworkError;
  const factory SdkError.storageError(String field0) = SdkError_StorageError;
  const factory SdkError.chainServiceError(String field0) = SdkError_ChainServiceError;
  const factory SdkError.maxDepositClaimFeeExceeded({
    required String tx,
    required int vout,
    Fee? maxFee,
    required BigInt requiredFeeSats,
    required BigInt requiredFeeRateSatPerVbyte,
  }) = SdkError_MaxDepositClaimFeeExceeded;
  const factory SdkError.missingUtxo({required String tx, required int vout}) = SdkError_MissingUtxo;
  const factory SdkError.lnurlError(String field0) = SdkError_LnurlError;
  const factory SdkError.signer(String field0) = SdkError_Signer;
  const factory SdkError.optimizationAlreadyRunning() = SdkError_OptimizationAlreadyRunning;
  const factory SdkError.optimizationCancelled() = SdkError_OptimizationCancelled;
  const factory SdkError.generic(String field0) = SdkError_Generic;
}
