// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'errors.freezed.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `SessionManagerError`, `StorageError`

@freezed
sealed class DepositClaimError with _$DepositClaimError {
  const DepositClaimError._();

  const factory DepositClaimError.maxDepositClaimFeeExceeded({
    required String tx,
    required int vout,
    Fee? maxFee,
    required BigInt requiredFeeSats,
    required BigInt requiredFeeRateSatPerVbyte,
  }) = DepositClaimError_MaxDepositClaimFeeExceeded;
  const factory DepositClaimError.missingUtxo({required String tx, required int vout}) =
      DepositClaimError_MissingUtxo;
  const factory DepositClaimError.generic({required String message}) = DepositClaimError_Generic;
}

@freezed
sealed class PasskeyError with _$PasskeyError implements FrbException {
  const PasskeyError._();

  const factory PasskeyError.prfError(PasskeyPrfError field0) = PasskeyError_PrfError;
  const factory PasskeyError.relayConnectionFailed(String field0) = PasskeyError_RelayConnectionFailed;
  const factory PasskeyError.nostrWriteFailed(String field0) = PasskeyError_NostrWriteFailed;
  const factory PasskeyError.nostrReadFailed(String field0) = PasskeyError_NostrReadFailed;
  const factory PasskeyError.keyDerivationError(String field0) = PasskeyError_KeyDerivationError;
  const factory PasskeyError.invalidPrfOutput(String field0) = PasskeyError_InvalidPrfOutput;
  const factory PasskeyError.mnemonicError(String field0) = PasskeyError_MnemonicError;
  const factory PasskeyError.invalidSalt(String field0) = PasskeyError_InvalidSalt;
  const factory PasskeyError.generic(String field0) = PasskeyError_Generic;
}

@freezed
sealed class PasskeyPrfError with _$PasskeyPrfError {
  const PasskeyPrfError._();

  const factory PasskeyPrfError.prfNotSupported() = PasskeyPrfError_PrfNotSupported;
  const factory PasskeyPrfError.userCancelled() = PasskeyPrfError_UserCancelled;
  const factory PasskeyPrfError.credentialNotFound() = PasskeyPrfError_CredentialNotFound;
  const factory PasskeyPrfError.authenticationFailed(String field0) = PasskeyPrfError_AuthenticationFailed;
  const factory PasskeyPrfError.prfEvaluationFailed(String field0) = PasskeyPrfError_PrfEvaluationFailed;
  const factory PasskeyPrfError.generic(String field0) = PasskeyPrfError_Generic;
}

@freezed
sealed class SdkError with _$SdkError implements FrbException {
  const SdkError._();

  const factory SdkError.sparkError(String field0) = SdkError_SparkError;
  const factory SdkError.insufficientFunds() = SdkError_InsufficientFunds;
  const factory SdkError.invalidUuid(String field0) = SdkError_InvalidUuid;
  const factory SdkError.invalidInput(String field0) = SdkError_InvalidInput;
  const factory SdkError.networkError(String field0) = SdkError_NetworkError;
  const factory SdkError.storageError(String field0) = SdkError_StorageError;
  const factory SdkError.chainServiceError(String field0) = SdkError_ChainServiceError;
  const factory SdkError.maxDepositClaimFeeExceeded({
    required String tx,
    required int vout,
    Fee? maxFee,
    required BigInt requiredFeeSats,
    required BigInt requiredFeeRateSatPerVbyte,
  }) = SdkError_MaxDepositClaimFeeExceeded;
  const factory SdkError.missingUtxo({required String tx, required int vout}) = SdkError_MissingUtxo;
  const factory SdkError.lnurlError(String field0) = SdkError_LnurlError;
  const factory SdkError.signer(String field0) = SdkError_Signer;
  const factory SdkError.generic(String field0) = SdkError_Generic;
}
