// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'errors.dart';
import 'frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'events.freezed.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `BindingEventListener`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `on_event`

@freezed
sealed class AutoOptimizationEvent with _$AutoOptimizationEvent {
  const AutoOptimizationEvent._();

  const factory AutoOptimizationEvent.started({required int totalRounds}) = AutoOptimizationEvent_Started;
  const factory AutoOptimizationEvent.roundCompleted({required int currentRound, required int totalRounds}) =
      AutoOptimizationEvent_RoundCompleted;
  const factory AutoOptimizationEvent.completed() = AutoOptimizationEvent_Completed;
  const factory AutoOptimizationEvent.cancelled() = AutoOptimizationEvent_Cancelled;
  const factory AutoOptimizationEvent.failed({required String error}) = AutoOptimizationEvent_Failed;
  const factory AutoOptimizationEvent.skipped() = AutoOptimizationEvent_Skipped;
}

@freezed
sealed class SdkEvent with _$SdkEvent {
  const SdkEvent._();

  const factory SdkEvent.synced() = SdkEvent_Synced;
  const factory SdkEvent.unclaimedDeposits({required List<DepositInfo> unclaimedDeposits}) =
      SdkEvent_UnclaimedDeposits;
  const factory SdkEvent.claimedDeposits({required List<DepositInfo> claimedDeposits}) =
      SdkEvent_ClaimedDeposits;
  const factory SdkEvent.paymentSucceeded({required Payment payment}) = SdkEvent_PaymentSucceeded;
  const factory SdkEvent.paymentPending({required Payment payment}) = SdkEvent_PaymentPending;
  const factory SdkEvent.paymentFailed({required Payment payment}) = SdkEvent_PaymentFailed;
  const factory SdkEvent.autoOptimization({required AutoOptimizationEvent optimizationEvent}) =
      SdkEvent_AutoOptimization;
  const factory SdkEvent.lightningAddressChanged({LightningAddressInfo? lightningAddress}) =
      SdkEvent_LightningAddressChanged;
  const factory SdkEvent.newDeposits({required List<DepositInfo> newDeposits}) = SdkEvent_NewDeposits;
}
