// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'errors.dart';
import 'frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `panic_message`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `CallbackPrfProvider`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `derive_prf_seed`, `is_prf_available`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Passkey>>
abstract class Passkey implements RustOpaqueInterface {
  /// Derive a wallet for a given wallet name.
  ///
  /// Uses the passkey PRF to derive a wallet from the wallet name.
  /// This works for both creating a new wallet and restoring an existing one.
  ///
  /// # Arguments
  /// * `wallet_name` - Optional wallet name string (defaults to "Default")
  Future<Wallet> getWallet({String? walletName});

  /// Check if passkey PRF is available on this device.
  Future<bool> isAvailable();

  /// List all wallet names published to Nostr for this passkey's identity.
  ///
  /// Requires 1 PRF call (for Nostr identity derivation).
  Future<List<String>> listWalletNames();

  /// Create a new Passkey instance using Dart callbacks.
  ///
  /// # Arguments
  /// * `derive_prf_seed` - Dart callback to derive a 32-byte seed from passkey PRF with a salt
  /// * `is_prf_available` - Dart callback to check if PRF-capable passkey is available
  /// * `relay_config` - Optional configuration for Nostr relay connections (uses default if None)
  factory Passkey({
    required FutureOr<Uint8List> Function(String) derivePrfSeed,
    required FutureOr<bool> Function() isPrfAvailable,
    NostrRelayConfig? relayConfig,
  }) => BreezSdkSparkLib.instance.api.cratePasskeyPasskeyNew(
    derivePrfSeed: derivePrfSeed,
    isPrfAvailable: isPrfAvailable,
    relayConfig: relayConfig,
  );

  /// Publish a wallet name to Nostr relays for this passkey's identity.
  ///
  /// Idempotent: if the wallet name already exists, it is not published again.
  /// Requires 1 PRF call.
  Future<void> storeWalletName({required String walletName});
}
