// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'errors.dart';
import 'frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `dart_error_to_prf`, `panic_message`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `CallbackPrfProvider`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `create_passkey`, `derive_seeds`, `is_supported`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<PasskeyClient>>
abstract class PasskeyClient implements RustOpaqueInterface {
  /// One-shot capability + configuration probe.
  Future<PasskeyAvailability> checkAvailability();

  /// Single-CTA onboarding: silent sign-in, fall through to register
  /// on `CredentialNotFound`. Mobile-only (iOS 18+ / Android 9+);
  /// see the core SDK docs for the cross-browser limitation.
  Future<ConnectWithPasskeyResponse> connectWithPasskey({required ConnectWithPasskeyRequest request});

  /// Label sub-object: list / publish labels for this passkey's identity.
  PasskeyLabels labels();

  /// Construct using Dart callbacks for the underlying `PrfProvider`.
  /// Hosts that don't drive registration can have `create_passkey`
  /// throw `PrfProviderError.PrfNotSupported` on the Dart side.
  factory PasskeyClient({
    required FutureOr<DeriveSeedsOutput> Function(DeriveSeedsRequest) deriveSeeds,
    required FutureOr<bool> Function() isSupported,
    required FutureOr<PasskeyCredential> Function(List<Uint8List>) createPasskey,
    String? breezApiKey,
    PasskeyConfig? config,
  }) => BreezSdkSparkLib.instance.api.cratePasskeyPasskeyClientNew(
    deriveSeeds: deriveSeeds,
    isSupported: isSupported,
    createPasskey: createPasskey,
    breezApiKey: breezApiKey,
    config: config,
  );

  /// First-time setup: drives the Dart-side `create_passkey` callback
  /// then derives the wallet seed.
  Future<RegisterResponse> register({required RegisterRequest request});

  /// Returning-user sign-in. Fast path with `label` set; cold-restore
  /// with discovery when `label` is `None`.
  Future<SignInResponse> signIn({required SignInRequest request});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<PasskeyLabels>>
abstract class PasskeyLabels implements RustOpaqueInterface {
  /// List labels published for this passkey's identity.
  Future<List<String>> list();

  /// Idempotently publish `label`.
  Future<void> store({required String label});
}
