// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'chain_service.dart';
import 'errors.dart';
import 'frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'sdk.dart';
import 'sdk_context.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SdkBuilder>>
abstract class SdkBuilder implements RustOpaqueInterface {
  Future<BreezSdk> build();

  factory SdkBuilder({required Config config, required Seed seed}) =>
      BreezSdkSparkLib.instance.api.crateSdkBuilderSdkBuilderNew(config: config, seed: seed);

  /// Sets a Rust-built chain service. Pass a handle from
  /// [`new_rest_chain_service`](crate::chain_service::new_rest_chain_service)
  /// to multiple `SdkBuilder`s to share one HTTP client across SDK instances.
  SdkBuilder withChainService({required BitcoinChainServiceHandle handle});

  SdkBuilder withDefaultStorage({required String storageDir});

  SdkBuilder withKeySet({required KeySetConfig config});

  SdkBuilder withRestChainService({
    required String url,
    required ChainApiType apiType,
    Credentials? credentials,
  });

  /// Threads a shared [`SdkContext`] into the builder.
  ///
  /// Construct the context once via
  /// [`new_shared_sdk_context`](crate::sdk_context::new_shared_sdk_context)
  /// and pass the same handle to every `SdkBuilder` whose SDKs should share
  /// its HTTP client, operator gRPC channels, and Breez backend gRPC client.
  SdkBuilder withSharedContext({required SdkContext context});
}
