// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'errors.dart';
import 'frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Process-shared SDK resources for Flutter integrations.
Future<SdkContext> newSharedSdkContext({required SdkContextConfig config}) =>
    BreezSdkSparkLib.instance.api.crateSdkContextNewSharedSdkContext(config: config);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SdkContext>>
abstract class SdkContext implements RustOpaqueInterface {}
