// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

SspConnectionManager newSspConnectionManager({String? userAgent}) =>
    BreezSdkSparkLib.instance.api.crateSspConnectionManagerNewSspConnectionManager(userAgent: userAgent);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SspConnectionManager>>
abstract class SspConnectionManager implements RustOpaqueInterface {}
